# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
