# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0002_auto_20190912_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='I found that his author has a beautiful way of expressing their emotions through paper and pencil'),
            preserve_default=False,
        ),
    ]
