# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='middle_name',
            field=models.CharField(default='none', max_length=45),
            preserve_default=False,
        ),
    ]
